const Actions = {
    JOIN: "JOIN",
    JOINED: "JOINED",
    DISCONNECTED: "DISCONNECTED",
    CHAT_SEND: "CHAT_SEND",
    BOARD_CHANGE: "BOARD_CHANGE",
    CODE_CHANGE: "CODE_CHANGE",
    PERMISSION_CHANGE: "PERMISSION_CHANGE"
}

export { Actions }